language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - "10"
before_script:
  - npm audit --only=prod --audit-level=critical
script: 
  - npm run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
